nc: 3  # number of classes
num_output: [1]
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, nn.Conv2d, [8, 3, 1, 1]],  # 0 (P0 / the same shape)
   [-1, 1, Conv, [64,  3, 2, 1, 1, 1, 'SiLU']],  # 1-P1/2
   [-1, 1, Conv, [128, 3, 2, 1, 1, 1, 'SiLU']],  # 2-P2/4
   [-1, 3, C3, [128, True, 1, 0.5, 'SiLU']],
   [-1, 1, Conv, [256, 3, 2, 1, 1, 1, 'SiLU']],  # 4-P3/8
   [-1, 6, C3, [256, True, 1, 0.5, 'SiLU']],
   [-1, 1, Conv, [512, 3, 2, 1, 1, 1, 'SiLU']],  # 6-P4/16
   [-1, 9, C3, [512, True, 1, 0.5, 'SiLU']],
   [-1, 1, Conv, [1024, 3, 2, 1, 1, 1, 'SiLU']],  # 8-P5/32
   [-1, 3, C3, [1024, True, 1, 0.5, 'SiLU']],
   [-1, 1, SPPF, [1024, 5, 'SiLU']],  # 10
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 7], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 14

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 5], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 18 (P3/8-small)

   [-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 4, 'nearest']], # 20 p2/
   [-1, 3, C3, [64, False]],  
   [-1, 1, nn.Upsample, [None, 2, 'nearest']], # 22
   [[-1, 0], 1, Concat, [1]],  # cat backbone P4
   [-1, 1, C3, [64, False]],
   [-1, 1, nn.Conv2d, [1, 1, 1]],  # 26 (P3/8-small)
  ]